// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"github.com/labstack/echo/v4"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Rank defines model for rank.
type Rank struct {
	EvPoints *float64 `json:"evPoints,omitempty"`
	Points   *int     `json:"points,omitempty"`
	Team     *string  `json:"team,omitempty"`
}

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse struct {
	Message *string `json:"message,omitempty"`
}

// ServerErrorResponse defines model for ServerErrorResponse.
type ServerErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse = []Rank

// CalculateMultipartBody defines parameters for Calculate.
type CalculateMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// CalculateMultipartRequestBody defines body for Calculate for multipart/form-data ContentType.
type CalculateMultipartRequestBody CalculateMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Calculate
	// (POST /calculate)
	Calculate(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Calculate converts echo context to params.
func (w *ServerInterfaceWrapper) Calculate(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Calculate(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/calculate", wrapper.Calculate)

}
