openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /calculate:
    get:
      parameters:
        - in: query
          name: leagueName
          schema:
            type: string
      summary: Calculate
      operationId: calculate
      tags:
        - Calculate
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/rank'
components:
  schemas:
    rank:
      type: object
      properties:
        team:
          type: string
        evPoints:
          type: number
          format: double
        points:
          type: integer