openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /calculate:
    post:
      summary: Calculate
      operationId: calculate
      tags:
        - Calculate
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file: # The field for the file upload
                  type: string
                  format: binary
                # You can include other optional text fields if needed
                # description:
                #   type: string
              required:
                - file
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '500':
          $ref: '#/components/responses/ServerErrorResponse'
components:
  schemas:
    rank:
      type: object
      properties:
        team:
          type: string
        evPoints:
          type: number
          format: double
        points:
          type: integer
  responses:
    SuccessResponse:
      description: Successful response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/rank'
    BadRequestResponse:
      description: Invalid request - missing or invalid parameters
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    ServerErrorResponse:
      description: Server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
