name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  push:
    branches:
      - main
jobs:
  publish_java:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish package
        run: mvn -U deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Generate code and push changes
        env:
          PAT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Generate the OpenAPI code
          echo "First 4 characters of PAT_TOKEN: ${PAT_TOKEN:0:4}"  # Print the first 4 characters

          go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
          oapi-codegen -generate types,client -o client.go src/main/resources/api.yaml 
          
          # Configure Git user and email
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Commit and push changes
          git add client.go
          git commit -m "Update generated code"
          git push