name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: java-toolchain/setup-java@v1
        with:
          java-version: '17'

      - name: Build Artifact
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
