name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  push:
    branches:
      - main
jobs:
  publish_java:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish package
        run: mvn -U deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Generate code and push changes
        run: |
          # Cleanup generated OpenAPI code
          rm server.go
          
          # Generate the OpenAPI code
          go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
          oapi-codegen -generate types,server -o server.go src/main/resources/api.yaml 
          
          # Configure Git user and email
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if there are changes to commit
          if [[ -n $(git status -s) ]]; then
            git add server.go
            git commit -m "Update generated code"
            git push --set-upstream origin $GITHUB_REF
          else
            echo "No changes to commit."
          fi
          jobs:
  publish_react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Init project
        run: npm init -y
      - name: Install dependencies
        run: npm install
      - name: Generate React code
        run: |
          openapi-generator-cli generate \
            -i src/main/resources/api.yaml \
            -g react \
            -o src/generated
      - name: Publish to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: generated-code
          path: src/generated
      - name: Publish package
        run: |
          npm publish --tag latest
